"""Add name to interpreter uploads

Revision ID: 0d9bdee82bdd
Revises: d8ea98b88f7c
Create Date: 2024-05-14 16:16:10.766050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d9bdee82bdd'
down_revision = 'd8ea98b88f7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interpreter_uploads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=512), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interpreter_uploads', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
