"""Create Form

Revision ID: 2dbfc3c3fe3e
Revises: b9568719e281
Create Date: 2024-03-31 00:15:24.542492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dbfc3c3fe3e'
down_revision = 'b9568719e281'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forms',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_account_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('review', 'open', 'closed', name='status'), nullable=False),
    sa.Column('public_key', sa.String(length=24), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_account_id'], ['user_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('forms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forms_public_key'), ['public_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_forms_user_account_id'), ['user_account_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forms_user_account_id'))
        batch_op.drop_index(batch_op.f('ix_forms_public_key'))

    op.drop_table('forms')
    # ### end Alembic commands ###
