"""Raise Form name limit

Revision ID: 6f6dc13e505f
Revises: 2dbfc3c3fe3e
Create Date: 2024-03-31 00:32:32.019050

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6f6dc13e505f'
down_revision = '2dbfc3c3fe3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forms', schema=None) as batch_op:
        batch_op.alter_column('user_account_id',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=128),
               type_=sa.String(length=512),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forms', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=512),
               type_=mysql.VARCHAR(length=128),
               existing_nullable=False)
        batch_op.alter_column('user_account_id',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=False)

    # ### end Alembic commands ###
