"""Raise role character limit

Revision ID: d72f0790ec46
Revises: f191e2f41d3b
Create Date: 2024-03-24 16:11:28.434755

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd72f0790ec46'
down_revision = 'f191e2f41d3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_accounts', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.VARCHAR(length=12),
               type_=sa.String(length=16),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_accounts', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.String(length=16),
               type_=mysql.VARCHAR(length=12),
               existing_nullable=True)

    # ### end Alembic commands ###
