"""Create interpreter upload

Revision ID: d8ea98b88f7c
Revises: f54f5d01c77e
Create Date: 2024-05-14 16:09:13.902790

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_file


# revision identifiers, used by Alembic.
revision = 'd8ea98b88f7c'
down_revision = 'f54f5d01c77e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interpreter_uploads',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('file', sqlalchemy_file.types.FileField(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interpreter_uploads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interpreter_uploads_owner_id'), ['owner_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interpreter_uploads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interpreter_uploads_owner_id'))

    op.drop_table('interpreter_uploads')
    # ### end Alembic commands ###
