"""Create Question

Revision ID: ef2d426de61b
Revises: 6f6dc13e505f
Create Date: 2024-03-31 01:24:43.762717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef2d426de61b'
down_revision = '6f6dc13e505f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('form_id', sa.BigInteger(), nullable=True),
    sa.Column('type', sa.Enum('open', 'selection', 'radio', name='type'), nullable=False),
    sa.Column('content', sa.String(length=256), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questions_form_id'), ['form_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questions_form_id'))

    op.drop_table('questions')
    # ### end Alembic commands ###
