"""Create Options

Revision ID: f169de0d4429
Revises: 247cfea76353
Create Date: 2024-04-17 17:05:21.712507

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f169de0d4429'
down_revision = '247cfea76353'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('options',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('question_id', sa.BigInteger(), nullable=True),
    sa.Column('content', sa.String(length=128), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('options', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_options_question_id'), ['question_id'], unique=False)

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_column('options')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('options', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True))

    with op.batch_alter_table('options', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_options_question_id'))

    op.drop_table('options')
    # ### end Alembic commands ###
