"""Add Exports

Revision ID: f54f5d01c77e
Revises: 26c1bf412d69
Create Date: 2024-05-04 20:57:10.651840

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_file


# revision identifiers, used by Alembic.
revision = 'f54f5d01c77e'
down_revision = '26c1bf412d69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exports',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Enum('csv', 'sqlite', name='type'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_process', 'done', name='status'), nullable=False),
    sa.Column('file', sqlalchemy_file.types.FileField(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exports_owner_id'), ['owner_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exports_owner_id'))

    op.drop_table('exports')
    # ### end Alembic commands ###
